//// Cross-language contract test for plays-stats.json.
////
//// This file (tests/fixtures/plays-stats.min.json) is generated by the
//// Rust emitter (tools/parse-plays stats::build_ranges) and pinned here.
//// This Gleam test decodes it with the production decoder; the Rust
//// test `cross_language_contract_fixture_matches` regenerates it from
//// the same inputs and compares value-for-value. If either side drifts,
//// one of the two tests fails.

import gleam/json
import gleam/list
import gleam/option
import gleeunit/should
import simplifile
import stats.{type RangeStats}

pub fn fixture_decodes_to_expected_stats_test() {
  let assert Ok(body) = simplifile.read("tests/fixtures/plays-stats.min.json")
  let assert Ok(data) = json.parse(body, stats.stats_data_decoder())

  data.ranges |> list.length |> should.equal(4)

  // The 1m range only contains Artist A (Artist B's play predates it).
  let assert #(stats.OneMonth, one_month) = range_for(data, stats.OneMonth)
  let assert [artist_a] = one_month.artists
  artist_a.name |> should.equal("Artist A")
  artist_a.plays |> should.equal(1)
  artist_a.image |> should.equal(option.None)
  let assert [album_a] = one_month.albums
  album_a.artist |> should.equal(option.Some("Artist A"))
  album_a.name |> should.equal("Album A")

  // All-time has both, Artist B first (more ms_played).
  let assert #(stats.AllTime, all_time) = range_for(data, stats.AllTime)
  let assert [artist_b, _artist_a] = all_time.artists
  artist_b.name |> should.equal("Artist B")
  let assert [track_beta, _track_alpha] = all_time.tracks
  track_beta.name |> should.equal("Beta")
  track_beta.artist |> should.equal(option.Some("Artist B"))
}

fn range_for(
  data: stats.StatsData,
  wanted: stats.Range,
) -> #(stats.Range, RangeStats) {
  let assert Ok(found) =
    list.find(data.ranges, fn(pair) {
      let #(range, _) = pair
      range == wanted
    })
  found
}
