[formatter.gleam]
command = "gleam"
options = ["format"]
includes = ["*.gleam"]
excludes = ["shared/src/gen/**"]

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.toml]
command = "taplo"
options = ["format"]
includes = ["*.toml"]

[formatter.shell]
command = "shfmt"
options = ["-w", "-i", "2", "-s"]
includes = ["*.sh", "*.bash"]

[formatter.nushell]
command = "nufmt"
includes = ["*.nu"]

[formatter.rust]
command = "rustfmt"
options = ["--edition", "2024"]
includes = ["*.rs"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
  "*.md",
  "*.yml",
  "*.yaml",
  "*.json",
  "*.webmanifest",
  "*.mjs",
  "*.css",
]
