//// Gather all site data for the SSG.
////
//// Each section fetches its own URL through the shared decoders in
//// `shared/src/atproto.gleam`. The `http_get` seam is injected from
//// `build.gleam` (which passes `transport.fetch_body`) so this module
//// is testable with stub functions and the network stays out of the
//// decision logic. Failure on a section logs a warning and returns an
//// empty value, so one slow PDS doesn't take the whole build down.

import atproto.{type DecodedRecord}
import data/frontmatter
import data/model.{type Post, type SiteData, SiteData}
import gen/alpha/feed/play.{type AlphaFeedPlay}
import gen/repo.{type Repo}
import gleam/io
import gleam/json
import gleam/list
import gleam/order
import gleam/string
import simplifile
import stats

/// A GET request that returns the response body as a string. The SSG
/// passes `transport.fetch_body`; tests pass canned stubs.
pub type HttpGet =
  fn(String) -> Result(String, String)

pub fn fetch_all(http_get: HttpGet) -> SiteData {
  let pinned_dids = fetch_pinned_dids(http_get)
  let profile = fetch_profile(http_get)
  let recent_plays = fetch_plays(http_get)
  let plays_stats = fetch_plays_stats()
  let repos = fetch_repos(http_get, pinned_dids)

  SiteData(profile:, recent_plays:, plays_stats:, repos:, posts: read_posts())
}

// --- plays stats (derived cache from tools/parse-plays, not live) ---

/// Read the precomputed top-N grids from `priv/cache/plays-stats.json`.
/// Generated by `just refresh`; absent cache degrades to an empty
/// aside rather than failing the build.
fn fetch_plays_stats() -> stats.StatsData {
  case simplifile.read("priv/cache/plays-stats.json") {
    Ok(body) ->
      case json.parse(body, stats.stats_data_decoder()) {
        Ok(data) -> data
        Error(e) ->
          log_fail("plays-stats", string.inspect(e), stats.empty_stats())
      }
    Error(e) -> log_fail("plays-stats", string.inspect(e), stats.empty_stats())
  }
}

// --- profile ---

fn fetch_profile(http_get: HttpGet) {
  case http_get(atproto.profile_url()) {
    Ok(body) ->
      case atproto.decode_profile(body) {
        Ok(profile) -> profile
        Error(e) -> log_fail_and_panic("profile", string.inspect(e))
      }
    Error(e) -> log_fail_and_panic("profile", e)
  }
}

// --- plays ---

fn fetch_plays(http_get: HttpGet) -> List(AlphaFeedPlay) {
  case http_get(atproto.plays_url()) {
    Ok(body) -> plays_from_body(body)
    Error(reason) -> log_fail("plays", reason, [])
  }
}

/// Pure: decode a plays `listRecords` body, falling back to the empty
/// list when a record fails to decode.
pub fn plays_from_body(body: String) -> List(AlphaFeedPlay) {
  case atproto.decode_plays(body) {
    Ok(plays) -> plays
    Error(e) -> log_fail("plays", string.inspect(e), [])
  }
}

// --- repos ---

fn fetch_repos(
  http_get: HttpGet,
  pinned_dids: List(String),
) -> List(DecodedRecord(Repo)) {
  case http_get(atproto.repos_url()) {
    Ok(body) ->
      case atproto.decode_repos(body) {
        Ok(records) ->
          records
          |> atproto.filter_repos_by_did(pinned_dids)
          |> list.map(atproto.resolve_repo_name)
        Error(e) -> log_fail("repos", string.inspect(e), [])
      }
    Error(e) -> log_fail("repos", e, [])
  }
}

// --- pinned DIDs ---

fn fetch_pinned_dids(http_get: HttpGet) -> List(String) {
  case http_get(atproto.pinned_dids_url()) {
    Ok(body) ->
      case atproto.decode_actor_profiles(body) {
        Ok(profiles) -> atproto.pinned_dids_from_profiles(profiles)
        Error(_) -> []
      }
    Error(_) -> []
  }
}

// --- posts (filesystem, not HTTP) ---

/// Read every post under `priv/posts/<slug>/index.md`. Includes
/// drafts (caller filters them). Fails the build if any post has
/// an invalid slug or frontmatter — see `data/frontmatter.gleam`
/// for what counts as invalid.
pub fn read_posts() -> List(Post) {
  case simplifile.read_directory("priv/posts") {
    Ok(entries) ->
      entries
      |> list.filter(fn(entry) {
        case simplifile.is_directory("priv/posts/" <> entry) {
          Ok(True) -> True
          _ -> False
        }
      })
      |> list.map(read_post)
      |> list.sort(by: compare_posts_desc)
    Error(_) -> []
  }
}

fn read_post(slug: String) -> Post {
  case frontmatter.is_valid_slug(slug) {
    False -> {
      io.println(
        "Error: post directory \""
        <> slug
        <> "\" is not a valid slug (lowercase letters, digits, and hyphens only).",
      )
      panic as "invalid slug"
    }
    True -> {
      let path = "priv/posts/" <> slug <> "/index.md"
      case simplifile.read(path) {
        Ok(content) ->
          case frontmatter.parse(slug, content) {
            Ok(post) -> post
            Error(e) -> {
              io.println("Error: " <> format_parse_error(slug, e))
              panic as "post parse failed"
            }
          }
        Error(e) -> {
          io.println(
            "Failed to read post " <> slug <> ": " <> string.inspect(e),
          )
          panic as "post read failed"
        }
      }
    }
  }
}

fn format_parse_error(slug: String, e: frontmatter.ParseError) -> String {
  case e {
    frontmatter.MissingField(_, field) ->
      "post \"" <> slug <> "\" is missing required field \"" <> field <> "\""
    frontmatter.InvalidDate(_, value) ->
      "post \""
      <> slug
      <> "\" has invalid date \""
      <> value
      <> "\" (expected YYYY-MM-DD)"
    frontmatter.InvalidYaml(_, error) ->
      "post \"" <> slug <> "\" has invalid frontmatter: " <> error
  }
}

fn compare_posts_desc(a: Post, b: Post) -> order.Order {
  string.compare(b.date, a.date)
}

// --- logging ---

fn log_fail_and_panic(what: String, reason: String) -> a {
  io.println("Failed to fetch " <> what <> ": " <> reason)
  panic as "required fetch failed"
}

fn log_fail(what: String, reason: String, fallback: a) -> a {
  io.println("Failed to fetch " <> what <> ": " <> reason)
  fallback
}
