//// Gather all site data for the SSG.
////
//// Each section fetches its own URL through the shared decoders in
//// `shared/src/atproto.gleam`. The `http_get` seam is injected from
//// `build.gleam` (which passes `transport.fetch_body`) so this module
//// is testable with stub functions and the network stays out of the
//// decision logic. Failure on a section logs a warning and returns an
//// empty value, so one slow PDS doesn't take the whole build down.

import atproto.{type DecodedRecord}
import data/frontmatter
import data/model.{type Post, type SiteData, SiteData}
import gen/actor/defs.{type ProfileViewDetailed}
import gen/feed/play.{type FeedPlay}
import gen/repo.{type Repo}
import gleam/int
import gleam/io
import gleam/json
import gleam/list
import gleam/option
import gleam/order
import gleam/result
import gleam/string
import simplifile
import stats
import tangled

/// A GET request that returns the response body as a string. The SSG
/// passes `transport.fetch_body`; tests pass canned stubs.
pub type HttpGet =
  fn(String) -> Result(String, String)

/// Gather all site data. Profile and posts are required — a failure
/// there fails the whole build so the caller can surface the reason.
/// Other sections (plays, repos, pinned DIDs) degrade to empty with a
/// logged warning.
pub fn fetch_all(http_get: HttpGet) -> Result(SiteData, String) {
  use profile <- result.try(fetch_profile(http_get))
  let pinned_dids = fetch_pinned_dids(http_get)
  let recent_plays = fetch_plays(http_get)
  let plays_stats = fetch_plays_stats()
  let repos = fetch_repos(http_get, pinned_dids)
  use posts <- result.try(read_posts())
  Ok(SiteData(profile:, recent_plays:, plays_stats:, repos:, posts:))
}

// --- plays stats (derived cache from tools/parse-plays, not live) ---

/// Read the precomputed top-N grids from `priv/cache/plays-stats.json`.
/// Generated by `just refresh`; absent cache degrades to an empty
/// aside rather than failing the build.
fn fetch_plays_stats() -> stats.StatsData {
  case simplifile.read("priv/cache/plays-stats.json") {
    Ok(body) ->
      case json.parse(body, stats.stats_data_decoder()) {
        Ok(data) -> data
        Error(e) ->
          log_fail(
            what: "plays-stats",
            reason: string.inspect(e),
            fallback: stats.empty_stats(),
          )
      }
    Error(e) ->
      log_fail(
        what: "plays-stats",
        reason: string.inspect(e),
        fallback: stats.empty_stats(),
      )
  }
}

// --- profile ---

fn fetch_profile(http_get: HttpGet) -> Result(ProfileViewDetailed, String) {
  case http_get(atproto.profile_url()) {
    Ok(body) ->
      case atproto.decode_profile(body) {
        Ok(profile) -> Ok(profile)
        Error(e) -> {
          let reason = string.inspect(e)
          io.println("Failed to fetch profile: " <> reason)
          Error("profile decode failed: " <> reason)
        }
      }
    Error(e) -> {
      io.println("Failed to fetch profile: " <> e)
      Error("profile fetch failed: " <> e)
    }
  }
}

// --- plays ---

fn fetch_plays(http_get: HttpGet) -> List(FeedPlay) {
  case http_get(atproto.plays_url()) {
    Ok(body) -> plays_from_body(body)
    Error(reason) -> log_fail(what: "plays", reason: reason, fallback: [])
  }
}

/// Pure: decode a plays `listRecords` body, falling back to the empty
/// list when a record fails to decode. Records that fail to decode
/// individually are dropped with a warning — a Teal schema change
/// silently shrinking the play list should be visible at build time.
pub fn plays_from_body(body: String) -> List(FeedPlay) {
  case atproto.decode_plays(body) {
    Ok(#(plays, drops)) -> {
      case drops > 0 {
        True ->
          io.println(
            "Warning: dropped "
            <> int.to_string(drops)
            <> " play record(s) that failed to decode",
          )
        False -> Nil
      }
      plays
    }
    Error(e) -> log_fail(what: "plays", reason: string.inspect(e), fallback: [])
  }
}

// --- repos ---

fn fetch_repos(
  http_get: HttpGet,
  pinned_dids: List(String),
) -> List(DecodedRecord(Repo)) {
  case http_get(atproto.repos_url()) {
    Ok(body) ->
      case atproto.decode_repos(body) {
        Ok(records) ->
          records
          |> tangled.filter_repos_by_did(pinned_dids)
          |> list.map(tangled.resolve_repo_name)
        Error(e) ->
          log_fail(what: "repos", reason: string.inspect(e), fallback: [])
      }
    Error(e) -> log_fail(what: "repos", reason: e, fallback: [])
  }
}

// --- pinned DIDs ---

fn fetch_pinned_dids(http_get: HttpGet) -> List(String) {
  case http_get(atproto.pinned_dids_url()) {
    Ok(body) ->
      case atproto.decode_actor_profiles(body) {
        Ok(profiles) -> tangled.pinned_dids_from_profiles(profiles)
        Error(e) ->
          log_fail(what: "pinned_dids", reason: string.inspect(e), fallback: [])
      }
    Error(e) -> log_fail(what: "pinned_dids", reason: e, fallback: [])
  }
}

// --- posts (filesystem, not HTTP) ---

/// Injected filesystem seam for posts. Mirrors `HttpGet` for the
/// network: the SSG passes real `simplifile` functions, tests pass
/// stubs. Keeps the I/O shell thin and the frontmatter logic pure.
pub type ReadDir =
  fn(String) -> Result(List(String), simplifile.FileError)

pub type IsDir =
  fn(String) -> Result(Bool, simplifile.FileError)

pub type ReadFile =
  fn(String) -> Result(String, simplifile.FileError)

/// Read every post under `priv/posts/<slug>/index.md`. Includes
/// drafts (caller filters them). Returns `Error` if any post has an
/// invalid slug or frontmatter — the build fails loudly rather than
/// shipping a half-broken site. Uses the real filesystem.
pub fn read_posts() -> Result(List(Post), String) {
  read_posts_with(
    read_dir: simplifile.read_directory,
    is_dir: simplifile.is_directory,
    read_file: simplifile.read,
  )
}

/// Same as `read_posts` but with injected filesystem functions so
/// tests can stub the `priv/posts` tree without touching disk.
pub fn read_posts_with(
  read_dir read_dir: ReadDir,
  is_dir is_dir: IsDir,
  read_file read_file: ReadFile,
) -> Result(List(Post), String) {
  case read_dir("priv/posts") {
    Ok(entries) -> {
      case
        list.try_map(entries, fn(entry) {
          case is_dir("priv/posts/" <> entry) {
            Ok(True) -> Ok(option.Some(entry))
            Ok(False) -> Ok(option.None)
            Error(e) ->
              Error(
                "is_directory failed for " <> entry <> ": " <> string.inspect(e),
              )
          }
        })
      {
        Error(e) -> Error(e)
        Ok(maybe_dirs) -> {
          let dirs =
            list.filter_map(maybe_dirs, fn(x) {
              case x {
                option.Some(v) -> Ok(v)
                option.None -> Error(Nil)
              }
            })
          case
            list.try_map(dirs, fn(slug) { read_post_with(slug, read_file) })
          {
            Ok(posts) -> Ok(list.sort(posts, by: compare_posts_desc))
            Error(e) -> Error(e)
          }
        }
      }
    }
    Error(e) -> Error("read_directory priv/posts failed: " <> string.inspect(e))
  }
}

fn read_post_with(slug: String, read_file: ReadFile) -> Result(Post, String) {
  case frontmatter.is_valid_slug(slug) {
    False ->
      Error(
        "post directory \""
        <> slug
        <> "\" is not a valid slug (lowercase letters, digits, and hyphens only)",
      )
    True -> {
      let path = "priv/posts/" <> slug <> "/index.md"
      case read_file(path) {
        Error(e) ->
          Error("failed to read post " <> slug <> ": " <> string.inspect(e))
        Ok(content) ->
          case frontmatter.parse(slug: slug, content: content) {
            Ok(post) -> Ok(post)
            Error(e) -> Error(format_parse_error(slug, e))
          }
      }
    }
  }
}

fn format_parse_error(slug: String, e: frontmatter.ParseError) -> String {
  case e {
    frontmatter.MissingField(_, field) ->
      "post \"" <> slug <> "\" is missing required field \"" <> field <> "\""
    frontmatter.InvalidDate(_, value) ->
      "post \""
      <> slug
      <> "\" has invalid date \""
      <> value
      <> "\" (expected YYYY-MM-DD)"
    frontmatter.InvalidYaml(_, error) ->
      "post \"" <> slug <> "\" has invalid frontmatter: " <> error
    frontmatter.InvalidSlug(_, reason) ->
      "post \"" <> slug <> "\" has invalid slug: " <> reason
  }
}

fn compare_posts_desc(a: Post, b: Post) -> order.Order {
  string.compare(b.date, a.date)
}

// --- logging ---

fn log_fail(
  what what: String,
  reason reason: String,
  fallback fallback: a,
) -> a {
  io.println("Failed to fetch " <> what <> ": " <> reason)
  fallback
}
